### ISSUE TITLE
Exception setting "RemoteApiAccessToken"

### ISSUE THREAD

**Issue by EvgeniiProkofev** [lwsrbrts/PoSHue#19]
Hi. Can you help me to understand, what I missed? [
![2018-12-13_21-36-06](https://user-images.githubusercontent.com/39096246/49963291-30f1f600-ff20-11e8-9de8-95d58dfbbb71.png)
](url) 

It's look similar to closed issue #6

**Comment by EvgeniiProkofev** [comment]
By the way, remote access token contains 28 symbols.

**Comment by EvgeniiProkofev** [comment]
Look like I should insert this in script:
`Set-StrictMode -Version 2.0`

**Comment by lwsrbrts** [comment]
Looking at your screenshot, you're declaring a variable called `$RemoteApiAccessToken` but then when constructing the object you're providing a variable called `$RemoteAccessToken` - the reason for the error is that the $RemoteAccessToken is null, hence why it's "zero".
