### ISSUE TITLE
Getting errors when running script.

### ISSUE THREAD

**Issue by duceduc** [lwsrbrts/PoSHue#20]
This is my script:

$ip = '192.168.1.1'
$apikey = 'larvwclfdlSLKzCcKFKGKJJ$dl0hZR4HfdvIDf'
Import-Module PoSHue

#!# Initiate Bridge with IP and API Key
$Bridge = [HueBridge]::New($ip, $apikey)

#!# Initiate Group with Group ID
$Group = [HueGroup]::New(3,$ip, $apikey)

#!# Switch off Lights
$Group.SwitchHueGroup('on')

#!# Shutdown PC
Stop-Computer -Force

If I install PoSHue 2.0.2, I get this error:
Exception setting “GroupFriendlyName”: “The character length (1) of the argument is too short. Specify an argument
with a length that is greater than or equal to “2”, and then try the command again.”
At C:\Program Files\WindowsPowerShell\Modules\PoSHue\2.0.2\PoSHue.ps1:1018 char:9
+ $this.GroupFriendlyName = $Name
+ CategoryInfo : NotSpecified: (:) [], SetValueInvocationException
+ FullyQualifiedErrorId : ExceptionWhenSetting

You cannot call a method on a null-valued expression.
At C:\Users\Duc\Desktop\shutdown.ps1:14 char:1
+ $Group.SwitchHueGroup(‘off’)
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

----
If I install PoSHue 2.2.0, I get this error:
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\PoSHue\2.2.0\PoSHue.ps1:1484 char:9
+ $this.XY.x = $Status.action.xy[0]
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray

You cannot call a method on a null-valued expression.
At C:\Users\Duc\Desktop\shutdown.ps1:14 char:1
+ $Group.SwitchHueGroup(‘on’)
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by lwsrbrts** [comment]
Thanks @duceduc - apologies for the delay, I haven't seen this until just now!

I'll have a look in to it.
